// AUTO-GENERATED by scripts/generate-shirts.mjs - do not edit by hand.
// Run `npm run shirts` (also runs before dev and build) to refresh.
export type GeneratedShirtPreset = {
  id: string;
  label: string;
  group: string;
  src: string;
};

export const GENERATED_SHIRT_PRESETS: GeneratedShirtPreset[] = [
  {
    id: "mens",
    label: "Blue shirt",
    group: "Male",
    src: "/overlays/shirts/mens.png",
  },
  {
    id: "women",
    label: "Women",
    group: "Female",
    src: "/overlays/shirts/women.png",
  },
  {
    id: "12",
    label: "12",
    group: "Other",
    src: "/overlays/shirts/12.png",
  },
  {
    id: "womem2",
    label: "Womem2",
    group: "Other",
    src: "/overlays/shirts/womem2.png",
  },
];
