// Scans public/overlays/shirts and writes the shirt preset catalog that the
// UI renders. Only transparent formats are included, and only files that
// actually exist, so adding or removing an image updates the selector.
//
// Optional overrides: public/overlays/shirts/shirts.meta.json
//   { "mens.png": { "label": "Blue shirt", "group": "Male" } }
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const shirtsDir = join(root, "public", "overlays", "shirts");
const outputFile = join(root, "src", "photo-print", "shirts.generated.ts");
const metaFile = join(shirtsDir, "shirts.meta.json");

const EXTENSIONS = new Set([".png", ".webp"]);

const LABELS = {
  "mens.png": { group: "Male", label: "Blue shirt" },
  "female1.png": { group: "Female", label: "Blouse 1" },
  "female2.png": { group: "Female", label: "Blouse 2" },
};

const GROUP_ORDER = { Male: 0, Female: 1, Other: 2 };

function readMeta() {
  if (!existsSync(metaFile)) return {};
  try {
    return JSON.parse(readFileSync(metaFile, "utf8")) || {};
  } catch (error) {
    console.warn(`shirts: could not parse ${metaFile}: ${error.message}`);
    return {};
  }
}

function titleCase(value) {
  return value
    .split(/[\s_-]+/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

function derive(file, meta) {
  const override = meta[file] || LABELS[file];
  if (override) return override;
  const base = file.replace(/\.[^.]+$/, "");
  const lower = base.toLowerCase();
  let group = "Other";
  let remainder = base;
  if (/^(male|men|mens|man)([-_ ]|$)/.test(lower)) {
    group = "Male";
    remainder = base.replace(/^(male|men|mens|man)[-_ ]?/i, "");
  } else if (/^(female|women|womens|woman)([-_ ]|$)/.test(lower)) {
    group = "Female";
    remainder = base.replace(/^(female|women|womens|woman)[-_ ]?/i, "");
  }
  const label = titleCase(remainder) || titleCase(base);
  return { group, label };
}

function main() {
  const meta = readMeta();
  let files = [];
  try {
    files = readdirSync(shirtsDir, { withFileTypes: true })
      .filter((entry) => entry.isFile())
      .map((entry) => entry.name)
      .filter((name) => EXTENSIONS.has(name.slice(name.lastIndexOf(".")).toLowerCase()));
  } catch {
    files = [];
  }

  const presets = files
    .map((file) => {
      const { group, label } = derive(file, meta);
      return {
        id: file.replace(/\.[^.]+$/, "").replace(/[^a-z0-9]+/gi, "-").toLowerCase(),
        label,
        group,
        src: `/overlays/shirts/${file}`,
      };
    })
    .sort((a, b) => {
      const groupDelta =
        (GROUP_ORDER[a.group] ?? GROUP_ORDER.Other) -
        (GROUP_ORDER[b.group] ?? GROUP_ORDER.Other);
      if (groupDelta !== 0) return groupDelta;
      return a.label.localeCompare(b.label);
    });

  const body = presets
    .map(
      (preset) =>
        `  {\n    id: ${JSON.stringify(preset.id)},\n    label: ${JSON.stringify(preset.label)},\n    group: ${JSON.stringify(preset.group)},\n    src: ${JSON.stringify(preset.src)},\n  },`,
    )
    .join("\n");

  const contents = `// AUTO-GENERATED by scripts/generate-shirts.mjs - do not edit by hand.
// Run \`npm run shirts\` (also runs before dev and build) to refresh.
export type GeneratedShirtPreset = {
  id: string;
  label: string;
  group: string;
  src: string;
};

export const GENERATED_SHIRT_PRESETS: GeneratedShirtPreset[] = [
${body}
];
`;

  writeFileSync(outputFile, contents, "utf8");
  console.log(`shirts: wrote ${presets.length} preset(s) -> ${outputFile}`);
}

main();
